apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      run: redis1
    name: redis1
  spec:
    ports:
    - name: port-1
      port: 6379
      protocol: TCP
      targetPort: 6379
    - name: port-2
      port: 16379
      protocol: TCP
      targetPort: 16379
    selector:
      run: redis1
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: gluster-heketi
    creationTimestamp: null
    name: redis1-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      run: redis1
    name: redis1
  spec:
    replicas: 1
    selector:
      run: redis1
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: redis1
      spec:
        containers:
        - command:
          - redis-server
          args:
          - /usr/local/etc/redis.conf
          - '--cluster-announce-ip'
          - '10.23.4.24'
          - '--cluster-announce-port'
          - '30287'
          - '--cluster-announce-bus-port'
          - '30404'
          image: redis-sharding-node 
          imagePullPolicy: Always
          name: redis1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data 
            name: data-volume
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: "redis1-pvc"
    test: false
    triggers:
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
kind: List
metadata: {}
